# Generated by Django 4.2.1 on 2023-05-10 12:49

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_small', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('audio', models.FilePathField(path=pathlib.PureWindowsPath('C:/For_Me/Coding/Python/course_work/root_site/media/audio'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.language')),
            ],
        ),
    ]
